name: "CDK Deploy"
description: "Deploy project using cdk"

inputs:
  environment:
    description: Environment to deploy
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: synced-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: deployer-prod-us-east-1
        role-skip-session-tagging: true
        role-duration-seconds: 1200

    - name: Setup Python
      uses: action/setup-python@v2
      with:
        python-version: '3.9.6'
    
    -name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.0'
      
    - name: Install dependencies
      env:
        AWS_ACCOUNT: ${{ inputs.environment }}
      working-directory: ./
      shell: bash
      run: |
        npm i -g aws-cdk
        python3 -m venv .env
        source .env/bin/activate
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -r layers/common/requirements.txt --target ./layers/common/python
    
    - name: CDK deploy
      env:
        AWS_ACCOUNT: ${{ inputs.environment }}
      working-directory: ./
      shell: bash
      run: |
        source .env/bin/activate
        cdk diff --no-color
        cdk deploy --require-approval=never
