name: Deploy

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: 3.12
  NODE_VERSION: 20.x

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - qa
          - production

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy"
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-cdk
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements-cdk.txt

      - name: Build common layer
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}'
        shell: bash
        run: |
          source .venv/bin/activate
          pip install -r src/common_layer/requirements.txt --target src/common_layer/python

      - name: Synthesize and deploy CDK project
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}'
        run: |
          source .venv/bin/activate
          cdk diff --no-color
          cdk synth
          cdk deploy --require-approval never
