name: Test

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'test'
    runs-on: [ ci-small ]
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        include:
          - name: shared
            tests: tests/shared
            cov: shared
          - name: src
            tests: tests/src
            cov: src
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: action/setup-python@v2
        with:
          python-version: '3.9.6'
      
      -name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.0'

      - name: Install flake8
        run: pip install flake8

      - name: Install dependencies
        working-directory: ./
        shell: bash
        run: |
          npm i -g aws-cdk
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
      
      - name: Run tests
        working-directory: ./
        shell: bash
        run: |
          source .env/bin/activate
          pytest ${{ matrix.tests }} --cov=${{ matrix.cov }}
