name: Test

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: 3.12
  NODE_VERSION: 20.x

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'test'
    runs-on: [ ci-small ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-cdk
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements-cdk.txt
          python -m pip install -r requirements.txt
      
      - name: Run tests
        shell: bash
        run: |
          source .env/bin/activate
          pytest tests --cov=src
